apiVersion: v1
kind: Service
metadata:
  name: common-modules
  namespace: default
  labels:
    app: common-modules

spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: common-modules

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-modules
  namespace: default

spec:
  replicas: 1
  selector:
    matchLabels:
      app: common-modules
  template:
    metadata:
      labels:
        app: common-modules
    spec:
      containers:
        - name: common-modules
          image: registry.jahiduls.mint/common-modules:local
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          env:
            - name: PORT
              value: "80"
