apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-config
  namespace: kube-logging
data:
  fluent.conf: |
    <label @FLUENT_LOG>
      <match fluent.**>
        @type null
        @id ignore_fluent_logs
      </match>
    </label>

    <source>
      @type tail
      @id in_tail_container_logs
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      exclude_path ["/var/log/containers/fluentd*.log"]
      read_from_head true
      <parse>
        @type regexp
        expression /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
    </filter>

    <filter kubernetes.var.log.containers.**>
      @type parser
      <parse>
        @type json
        json_parser json
      </parse>
      replace_invalid_sequence true
      emit_invalid_record_to_error false
      key_name log
      reserve_data true
    </filter>

    <match kubernetes.var.log.containers.**kube-logger**.log>
      @type null
    </match>

    <match kubernetes.var.log.containers.**kube-system**.log>
      @type null
    </match>

    <match kubernetes.var.log.containers.**kube-ingress**.log>
      @type null
    </match>

    <match kubernetes.var.log.containers.**kube-load-balancer**.log>
      @type null
    </match>

    <match kubernetes.var.log.containers.**kube-storage.**log>
      @type null
    </match>

    <match kubernetes.var.log.containers.**local-path-storage**.log>
      @type null
    </match>

    <match **>
      @type stdout
    </match>
