version: '3'

networks:
  frontend-network:
    driver: bridge

services:
  gateway:
    image: gateway:local
    container_name: gateway
    build: gateway/
    restart: unless-stopped
    networks:
      - frontend-network
    ports:
      - 80:80
    depends_on:
      - page-service
      - layout-service
      - content-service
      - widget-service
      - nav-widget
      - footer-widget
      - home-widget
      - about-widget
  page-service:
    image: page.service:local
    container_name: page.service
    build: page-service/
    restart: unless-stopped
    networks:
      - frontend-network
    environment:
      - PORT=80
    expose:
      - 80
  layout-service:
    image: layout.service:local
    container_name: layout.service
    build: layout-service/
    restart: unless-stopped
    networks:
      - frontend-network
    environment:
      - PORT=80
    expose:
      - 80
  content-service:
    image: content.service:local
    container_name: content.service
    build: content-service/
    restart: unless-stopped
    networks:
      - frontend-network
    environment:
      - PORT=80
    expose:
      - 80
  widget-service:
    image: widget.service:local
    container_name: widget.service
    build: widget-service/
    restart: unless-stopped
    networks:
      - frontend-network
    environment:
      - PORT=80
    expose:
      - 80
  # widgets
  nav-widget:
    image: nav.widget:local
    container_name: nav.widget
    build: widgets/nav/
    restart: unless-stopped
    networks:
      - frontend-network
    environment:
      - PORT=80
    expose:
      - 80
  footer-widget:
    image: footer.widget:local
    container_name: footer.widget
    build: widgets/footer/
    restart: unless-stopped
    networks:
      - frontend-network
    environment:
      - PORT=80
    expose:
      - 80
  home-widget:
    image: home.widget:local
    container_name: home.widget
    build: widgets/home/
    restart: unless-stopped
    networks:
      - frontend-network
    environment:
      - PORT=80
    expose:
      - 80
  about-widget:
    image: about.widget:local
    container_name: about.widget
    build: widgets/about/
    restart: unless-stopped
    networks:
      - frontend-network
    environment:
      - PORT=80
    expose:
      - 80
  tictactoe-widget:
    image: tictactoe.widget:local
    container_name: tictactoe.widget
    build: widgets/tic-tac-toe/
    restart: unless-stopped
    networks:
      - frontend-network
    environment:
      - PORT=80
    expose:
      - 80
