version: '3'

networks:
  frontend:
    name: frontend-network
    driver: bridge
  widget:
    name: widget-network
    driver: bridge
  backend:
    name: backend-network
    driver: bridge

services:
  gateway:
    image: gateway:local
    container_name: gateway
    build: gateway/
    restart: unless-stopped
    networks:
      - frontend
      - backend
      - widget
    ports:
      - 80:80
    depends_on:
      - web-service
      - page-service
      - layout-service
      - content-service
      - widget-service
  page-service:
    image: page.service:local
    container_name: page.service
    build: page-service/
    restart: unless-stopped
    networks:
      - frontend
    environment:
      - PORT=80
    expose:
      - 80
  web-service:
    image: web.service:local
    container_name: web.service
    build: web-service/
    restart: unless-stopped
    networks:
      - frontend
    environment:
      - PORT=80
    expose:
      - 80
  layout-service:
    image: layout.service:local
    container_name: layout.service
    build: layout-service/
    restart: unless-stopped
    networks:
      - frontend
    environment:
      - PORT=80
    expose:
      - 80
  content-service:
    image: content.service:local
    container_name: content.service
    build: content-service/
    restart: unless-stopped
    networks:
      - frontend
    environment:
      - PORT=80
    expose:
      - 80
  widget-service:
    image: widget.service:local
    container_name: widget.service
    build: widget-service/
    restart: unless-stopped
    networks:
      - frontend
    environment:
      - PORT=80
    expose:
      - 80
