---

- name: Setup new machine
  hosts: localhost
  connection: local
  vars:
    user: "{{ lookup('env', 'USER') }}"
    data_dirs:
      - backups
      - library
      - docker
      - kubernetes
  tasks:
    - name: Install necessary packages
      become: true
      apt:
        pkg:
          - curl
          - git
          - tree
          - ncdu
          - ripgrep 
        state: latest
        update_cache: true
    - name: Setup data dir
      become: true
      file:
        path: "/data"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0755'
        state: directory
    - name: Setup data subdirs
      file:
        path: "/data/{{ item }}"
        state: directory
      loop: "{{ data_dirs }}"

- name: Setup docker and docker-compose
  hosts: localhost
  connection: local
  vars:
    user: "{{ lookup('env', 'USER') }}"
    compose_version: 1.29.2
    ubuntu_codename: focal
  tasks:
    - name: Install docker deps
      become: true
      apt:
        pkg: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: latest
        update_cache: true
    - name: Add docker gpg apt key
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /etc/apt/trusted.gpg.d/docker.gpg
    - name: Add docker repository
      become: true
      apt_repository:
        filename: docker
        repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu {{ ubuntu_codename }} stable
        state: present
    - name: Update apt and install docker-ce
      become: true
      apt:
        name: docker-ce
        state: latest
        update_cache: true
    - name: Add user to docker group
      become: true
      user:
        name: "{{ user }}"
        group: docker
        append: true
    - name: Install docker-compose
      shell: >
        sudo curl -L https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

- name: Setup vim
  hosts: localhost
  connection: local
  vars:
    user: "{{ lookup('env', 'USER') }}"
    home: "{{ lookup('env', 'HOME') }}"
  tasks:
    - name: Install vim
      apt:
        name: vim
        state: latest
    - name: Stat vundle dir
      stat: path={{ home }}/.vim/bundle/Vundle.vim
      register: vundle_dir
    - name: Install vundle
      command:  git clone https://github.com/VundleVim/Vundle.vim.git {{ home }}/.vim/bundle/Vundle.vim
      when: vundle_dir.stat.exists == False


