---
# PreRequisites:
#   - Have ssh keys setup to push/pull to/from github

- name: Setup dotfiles
  hosts: localhost
  connection: local
  vars:
    user: "{{ lookup('env', 'USER') }}"
    home: "{{ lookup('env', 'HOME') }}"
    dotfiles_path: "{{ home }}/.dotfiles"
  tasks:
    - name: Install zsh
      become: yes
      apt:
        name: zsh
        state: latest
        update_cache: yes
    - name: Stat dotfiles local repo
      stat: path={{ dotfiles_path }}
      register: dotfiles_dir
    - name: Clone repo
      command: git clone --bare git@github.com:jahid90/dotfiles.git {{ dotfiles_path }}
      when: dotfiles_dir.stat.exists == False
    - name: Setup git to ignore untracked files
      command: git --git-dir={{ dotfiles_path }} --work-tree={{ home }} config --local status.showUntrackedFiles no
    - name: Stat zsh config file
      stat: path={{ home }}/.zshrc
      register: zsh_config
    - name: Make a backup of existing config
      command: mv {{ home }}/.zshrc {{ home }}/.zshrc.bak
      when: zsh_config.stat.exists
    - name: Checkout branch
      command: git --git-dir={{ dotfiles_path }} --work-tree={{ home }} checkout
    - name: Stat ohmyzsh dir
      stat: path={{ home }}/.oh-my-zsh
      register: ohmyzsh_dir
    - name: Download oh-my-zsh install script
      get_url:
        url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/install-oh-my-zsh.sh
        mode: '+x'
        force: yes
      when: ohmyzsh_dir.stat.exists == False
    - name: Install oh-my-zsh
      command: /tmp/install-oh-my-zsh.sh
      when: ohmyzsh_dir.stat.exists == False
    - name: Stat auto-suggestions
      stat: path={{ home }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
      register: auto_suggestions_dir
    - name: Download auto-suggestions plugin
      command: git clone https://github.com/zsh-users/zsh-autosuggestions {{ home }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
      when: auto_suggestions_dir.stat.exists == False
    - name: Enable auto-suggestions plugin
      debug:
        msg: "Add entry in plugins var in ~/.zshrc file: `plugins=(... zsh-autosuggestions)`"
    - name: Source configs
      debug:
        msg: "Dotfiles setup complete; source the config file `source ~/.zshrc` or open a new shell"

