---

# Pre-requisites:
#   - Have ssh keys setup to push/pull to/from github

- name: Setup dotfiles
  hosts: localhost
  connection: local
  vars:
    user: "{{ lookup('env', 'USER') }}"
    home: "{{ lookup('env', 'HOME') }}"
    dotfiles_path: "{{ home }}/.dotfiles"
  tasks:
    - name: Install zsh
      become: true
      apt:
        name: zsh
        state: latest
        update_cache: true
    - name: Clone dotfiles repo
      shell: >
        git clone --bare git@github.com:jahid90/dotfiles.git {{ dotfiles_path }}
      args:
        creates: "{{ ansible_env.HOME }}/.dotfiles"
      register: dotfiles_installed
    # - debug: var=dotfiles_installed
    - name: Setup git to ignore untracked files
      command: git --git-dir={{ dotfiles_path }} --work-tree={{ home }} config --local status.showUntrackedFiles no
      when: dotfiles_installed.changed
    - name: Checkout branch
      command: git --git-dir={{ dotfiles_path }} --work-tree={{ home }} checkout
      when: dotfiles_installed.changed
    - name: Install oh-my-zsh
      shell: >
        curl -o- https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.ohmyzsh"
    - name: Clone auto-suggestions plugin
      shell: >
        git clone https://github.com/zsh-users/zsh-autosuggestions {{ home }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
      args: 
        creates: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    - name: Enable auto-suggestions plugin
      debug:
        msg: "Add entry in plugins var in ~/.zshrc file: `plugins=(... zsh-autosuggestions)`"
    - name: Source configs
      debug:
        msg: "Dotfiles setup complete; start a new session (`exec zsh`) or open a new shell"

