---
- name: Setup VS Code
  hosts: localhost
  connection: local
  vars:
    user: "{{ lookup('env', 'USER') }}"
  tasks:
    - name: Install pre-reqs
      become: yes
      apt:
        pkg:
          - wget
          - gpg
          - apt-transport-https
        state: latest
        update_cache: yes
    - name: Add vscode gpg apt key
      become: yes
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc 
        state: present
    - name: Add vscode repository
      become: yes
      apt_repository:
        filename: vscode
        repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/microsoft.gpg] https://packages.microsoft.com/repos/code stable main
        state: present
    - name: Update apt and install vscode
      become: yes
      apt:
        name: code
        state: latest
        update_cache: yes

