---

- name: Setup Microsoft Edge
  hosts: localhost
  connection: local
  vars:
    user: "{{ lookup('env', 'USER') }}"
  tasks:
    - name: Install pre-reqs
      become: true
      apt:
        pkg:
          - wget
          - gpg
          - apt-transport-https
        state: latest
        update_cache: true
    - name: Add edge gpg apt key
      become: true
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc 
        state: present
        keyring: /etc/apt/trusted.gpg.d/microsoft.gpg
    - name: Add vscode repository
      become: true
      apt_repository:
        filename: microsoft-edge
        repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/microsoft.gpg] https://packages.microsoft.com/repos/edge stable main
        state: present
    - name: Update apt and install edge
      become: true
      apt:
        name: microsoft-edge-stable
        state: latest
        update_cache: true

