version: '3'

networks:
  traefik:
    name: traefik
    driver: bridge

services:
  common-widgets:
    image: registry.jahiduls.mint/common-widgets:local
    container_name: common-widgets
    build: common/
    restart: unless-stopped
    networks:
      - traefik
    environment:
      - PORT=80
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.common-widgets.entrypoints=websecure
      - traefik.http.routers.common-widgets.rule=Host(`jahiduls.mint`) && PathPrefix(`/widgets`)
      - traefik.http.routers.common-widgets.tls=true
      - traefik.http.routers.common-widgets.middlewares=common-widgets-stripprefix
      - traefik.http.middlewares.common-widgets-stripprefix.stripprefix.prefixes=/widgets
  common-modules:
    image: registry.jahiduls.mint/common-modules:local
    container_name: common-modules
    build: modules/
    restart: unless-stopped
    networks:
      - traefik
    environment:
      - PORT=80
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.common-modules.entrypoints=websecure
      - traefik.http.routers.common-modules.rule=Host(`jahiduls.mint`) && PathPrefix(`/modules`)
      - traefik.http.routers.common-modules.tls=true
      - traefik.http.routers.common-modules.middlewares=common-modules-stripprefix
      - traefik.http.middlewares.common-modules-stripprefix.stripprefix.prefixes=/modules
