version: 6
variables:
  environment: staging
  domain: home.io
  gateway: 172.100.0.1
  subnet: 172.100.0.0/16
  network: staging
commands:
  start:
    description: Start up the docker infra environment
    steps:
      - name: setup:infra:network
        run: docker network create --driver=bridge --subnet={{ .subnet }} --gateway={{ .gateway }} {{ .network }} || echo 'Network already exists'
      - name: generate:dockerfile
        run: composer compose --in Dockerfile.tmpl --values values.yaml --out Dockerfile
      - name: generate:config:builder
        run: docker build -t builder:latest .
      - name: generate:compose:file
        run: composer compose --in docker-compose.yaml.tmpl --values values.yaml --out docker-compose.yaml
      - name: run:config:builder
        run: docker run -d --name builder builder:latest
      - name: copy:docker:config
        run: docker cp builder:/traefik/Dockerfile ./traefik/Dockerfile
      - name: copy:cert:config
        run: docker cp builder:/traefik/configuration/certs.toml ./traefik/configuration/certs.toml
      - name: copy:certs
        run: docker cp builder:/traefik/configuration/certs ./traefik/configuration/
      - name: remove:docker:container
        run: docker container stop builder && docker container rm builder
      - name: remove:config:builder
        run: docker image rm builder:latest
      - name: run:traefik:container
        run: docker-compose up -d
  stop:
    description: Stop the docker infra environment
    steps:
      - name: stop:traefik:container
        run: docker-compose down
  open:dashboard:
    description: Open the ingress open:dashboard
    steps:
      - name: open:browser
        run: nohup xdg-open https://traefik.{{ .domain }} > /dev/null 2>&1
