version: '3'

networks:
  traefik:
    name: traefik
    driver: bridge

services:
  web-service:
    image: registry.jahiduls.mint/web-service:local
    container_name: web-service
    build: {{ .Values.web_service_path }}
    restart: unless-stopped
    networks:
      - traefik
    environment:
      - PORT=80
      - ASSEMBLER_SERVICE_URI=assembler-service
      - SERVICE_NAME=web-service
      - ZIPKIN_URI=http://zipkin:9411/api/v2/spans
      #- EnableLogTraceToConsole=true
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-service.entrypoints=websecure
      - traefik.http.routers.web-service.rule=Host(`jahiduls.mint`)
      - traefik.http.routers.web-service.tls=true
  assembler-service:
    image: registry.jahiduls.mint/assembler-service:local
    container_name: assembler-service
    build: {{ .Values.assembler_service_path }}
    restart: unless-stopped
    networks:
      - traefik
    environment:
      - PORT=80
      - PAGE_SERVICE_URI=page-service
      - SERVICE_NAME=assembler-service
      - ZIPKIN_URI=http://zipkin:9411/api/v2/spans
      #- EnableLogTraceToConsole=true
    expose:
      - 80
  page-service:
    image: registry.jahiduls.mint/page-service:local
    container_name: page-service
    build: {{ .Values.page_service_path }}
    restart: unless-stopped
    networks:
      - traefik
    environment:
      - PORT=80
      - LAYOUT_SERVICE_URI=layout-service
      - CONTENT_SERVICE_URI=content-service
      - WIDGET_SERVICE_URI=widget-service
      - SERVICE_NAME=page-service
      - ZIPKIN_URI=http://zipkin:9411/api/v2/spans
      #- EnableLogTraceToConsole=true
    expose:
      - 80
  layout-service:
    image: registry.jahiduls.mint/layout-service:local
    container_name: layout-service
    build: {{ .Values.layout_service_path }}
    restart: unless-stopped
    networks:
      - traefik
    environment:
      - PORT=80
      - SERVICE_NAME=layout-service
      - ZIPKIN_URI=http://zipkin:9411/api/v2/spans
      #- EnableLogTraceToConsole=true
    expose:
      - 80
  content-service:
    image: registry.jahiduls.mint/content-service:local
    container_name: content-service
    build: {{ .Values.content_service_path }}
    restart: unless-stopped
    networks:
      - traefik
    environment:
      - PORT=80
      - SERVICE_NAME=content-service
      - ZIPKIN_URI=http://zipkin:9411/api/v2/spans
      #- EnableLogTraceToConsole=true
    expose:
      - 80
  widget-service:
    image: registry.jahiduls.mint/widget-service:local
    container_name: widget-service
    build: {{ .Values.widget_service_path }}
    restart: unless-stopped
    networks:
      - traefik
    environment:
      - PORT=80
      - SERVICE_NAME=widget-service
      - ZIPKIN_URI=http://zipkin:9411/api/v2/spans
      #- EnableLogTraceToConsole=true
    expose:
      - 80
