apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
  labels:
    app: auth-service

spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: auth-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: default

spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth
          image: registry.jahiduls.mint/auth-service:local
          ports:
            - containerPort: 80
              name: http
          env:
            - name: PORT
              value: '80'
            - name: MONGO_USER
              value: auth
            - name: MONGO_PASSWORD
              value: auth
            - name: MONGO_HOST
              value: mongodb.kube-storage
            - name: MONGO_PORT
              value: '27017'
            - name: MONGO_DATABASE
              value: auth
