apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: server
  labels:
    app: web-service

spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: web-service

---
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: web-service
  namespace: server
  labels:
    app: web-service

spec:
  weighted:
    services:
      - name: web-service
        weight: 1
        port: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
  namespace: server

spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-service
  template:
    metadata:
      labels:
        app: web-service
    spec:
      containers:
        - name: web
          image: web-service:local
          ports:
            - containerPort: 80
              name: http
          env:
            - name: PORT
              value: "80"
            - name: ASSEMBLER_SERVICE_URI
              value: assembler-service

# ---
# kind: Ingress
# apiVersion: networking.k8s.io/v1
# metadata:
#   name: web-service
#   namespace: server
#   annotations:
#     traefik.ingress.kubernetes.io/router.entrypoints: web

# spec:
#   rules:
#   - host: jahiduls.kube
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name:  web-service
#             port:
#               number: 80
#       - path: /widgets
#         pathType: Prefix
#         backend:
#           service:
#             name: common-widgets
#             port:
#               number: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute
  namespace: server

spec:
  entryPoints:
    - web
  routes:
    - match: Host(`jahiduls.kube`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: web-service
          port: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix-widgets
  namespace: server

spec:
  stripPrefix:
    prefixes:
      - /widgets
