version: '4'
commands:
  cluster:generate: composer compose --in cluster.tmpl --values values.yaml --out cluster.yaml
  cluster:down: kind delete cluster --name local
  cluster:up: kind create cluster --config cluster.yaml --name local
  ingress:up: find ingress/ -iname '*.yaml' | sort | xargs -I{} kubectl apply -f {}
  lb:up: find loadbalancer/ -iname '*.yaml' | sort | xargs -I{} kubectl apply -f {}
  logging:up: find logging/ -iname '*.yaml' | sort | xargs -I{} kubectl apply -f {}
  ns:up: find namespaces/ -iname '*.yaml' | sort | xargs -I{} kubectl apply -f {}
  server:up: find server/ -iname '*.yaml' | sort | xargs -I{} kubectl apply -f {}
  storage:up: find storage/ -iname '*.yaml' | sort | xargs -I{} kubectl apply -f {}
  telemetry:up: find telemetry/ -iname '*.yaml' | sort | xargs -I{} kubectl apply -f {}
  tools:up: find tools/ -iname '*.yaml' | sort | xargs -I{} kubectl apply -f {}
  widgets:up: find widgets/ -iname '*.yaml' | sort | xargs -I{} kubectl apply -f {}

