version: "5"
commands:
  - alias: cluster:generate
    command: composer compose --in cluster.tmpl --values values.yaml --out cluster.yaml
    description: "Generate cluster config"
  - alias: cluster:up
    command: kind create cluster --config cluster.yaml --name local
    description: "Create a local kubernetes cluster"
    depends:
      - cluster:generate
  - alias: cluster:down
    command: kind delete cluster --name local
    description: "Delete the local kubernetes cluster"
  - alias: ns:up
    command: find namespaces/ -iname '*.yaml' | sort | xargs -I{} kubectl apply -f {}
  - alias: lb:up
    command: find loadbalancer/ -iname '*.yaml' | sort | xargs -I{} kubectl apply -f {}
    description: "Setup load balancer"
    depends:
      - ns:up
  - alias: ingress:up
    command: find ingress/ -iname '*.yaml' | sort | xargs -I{} kubectl apply -f {}
    description: "Setup cluster ingress"
    depends:
      - ns:up
  - alias: logging:up
    command: find logging/ -iname '*.yaml' | sort | xargs -I{} kubectl apply -f {}
  - alias: server:up
    command: find server/ -iname '*.yaml' | sort | xargs -I{} kubectl apply -f {}
  - alias: storage:up
    command: find storage/ -iname '*.yaml' | sort | xargs -I{} kubectl apply -f {}
  - alias: telemetry:up
    command: find telemetry/ -iname '*.yaml' | sort | xargs -I{} kubectl apply -f {}
  - alias: tools:up
    command: find tools/ -iname '*.yaml' | sort | xargs -I{} kubectl apply -f {}
  - alias: widgets:up
    command: find widgets/ -iname '*.yaml' | sort | xargs -I{} kubectl apply -f {}
