apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pi-nfs-storage
provisioner: jahiduls.io/nfs-pi
parameters:
  archiveOnDelete: "false"
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-nfs-storage
provisioner: jahiduls.io/nfs-local
parameters:
  archiveOnDelete: "false"
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
