apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-nfs-client-provisioner
  labels:
    app: local-nfs-client-provisioner
  namespace: kube-storage

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: local-nfs-client-provisioner
  template:
    metadata:
      labels:
        app: local-nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: local-nfs-client-provisioner
          image: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          volumeMounts:
            - name: local-nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: jahiduls.io/nfs-local
            - name: NFS_SERVER
              value: 192.168.0.165
            - name: NFS_PATH
              value: /data/kubernetes
      volumes:
        - name: local-nfs-client-root
          nfs:
            server: 192.168.0.165
            path: /data/kubernetes
