apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: {{ .Values.namespace }}
  labels:
    app: zipkin

spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: zipkin
  selector:
    app: zipkin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: {{ .Values.namespace }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin:latest
        ports:
        - containerPort: 9411
          name: zipkin

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: zipkin
  namespace: {{ .Values.namespace }}

spec:
  entryPoints:
    - web
  routes:
    - match: Host(`zipkin.jahiduls.kube`)
      kind: Rule
      services:
        - name: zipkin
          port: 80
