apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-lb
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.200.255.1-172.200.255.254
