apiVersion: v1
kind: Namespace
metadata:
  name: mariadb

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: mariadb
  labels:
    app: mariadb
spec:
  ports:
  - port: 3306
    name: mariadb
  clusterIP: None
  selector:
    app: mariadb

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: mariadb
spec:
  serviceName: mariadb
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mariadb
        image: ghcr.io/linuxserver/mariadb:alpine
        ports:
        - containerPort: 3306
          name: mariadb
        env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: TZ
          value: Asia/Kolkata
        volumeMounts:
        - name: mariadb-data
          mountPath: /config
  volumeClaimTemplates:
  - metadata:
      name: mariadb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-nfs-storage
      resources:
        requests:
          storage: 500Mi
